theme: jekyll-theme-minimal
title: Awesome Sustainable Technology
description: Open technology projects sustaining stable climate, energy supply and vital natural resources
logo: earth.gif
show_downloads: "false"
