site_name: 'Open Sustainable Technology'
site_url: 'https://OpenSustain.tech'
site_description: 'Open technology projects sustaining stable climate, energy supply and vital natural resources'
repo_name: 'protontypes/open-sustainable-technology'
repo_url: 'https://github.com/protontypes/open-sustainable-technology'
nav:
  - "Truly Sustainable is Open": "index.md"
  - "Communities": "COMMUNITIES.md"
  - "Educational Resources": "EDUCATION.md"
  - "Contribute": "CONTRIBUTING.md"

theme:
  name: 'material'
  custom_dir: 'docs/overrides'
  logo: 'logo.png'
  favicon: 'favicon.png'
  palette:
        primary: 'teal'
        accent: 'light'
  features:
    - navigation.instant
    - navigration.tabs
    - search.highlight
    - search.suggest
    - navigation.tabs
    - toc.integrate
    - header.autohide

extra_css:
    - css/extra.css

markdown_extensions:
  - meta
  - toc:
      permalink: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/protontypes
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/protontypes

copyright: Copyright &copy;  2020 protontypes
