name: Send URLs from Commit Message as Toots

on:
  push:
    branches:
      - main
      - agri
  
jobs:
  toot:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'https')"
    steps:
      - name: Extract Line with URL as Toot
        env:
          default_hashtags: " #climate #sustainability"
        run: |
              echo -e "${{ github.event.head_commit.message }}" >> toot
              toot_message="$(cat toot | grep -m 1 https*)"$default_hashtags
              echo "toot_message=$toot_message" >> $GITHUB_ENV
      
      - name: Send Toot
        uses: rzr/fediverse-action@master
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          host: "fosstodon.org"
          message: ${{ env.toot_message }}
